name: build wheel
on:
  workflow_dispatch:
    inputs:
      xapian_version:
        type: choice
        description: Xapian version
        default: "1.4.22"
        options:
          - "1.4.22"
          - "1.4.21"
          - "1.4.20"
          - "1.4.19"
          - "1.4.18"
      python_version:
        type: choice
        description: Python version
        default: "3.10"
        options:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with: 
          platforms: linux/arm64
      - name: Build wheel
        run: |
          docker run -e XAPIAN_VERSION=${{inputs.xapian_version}} -e PYVER=${{inputs.python_version}} -v `pwd`/scripts:/scripts/ -v `pwd`/wheelhouse:/app/wheelhouse roifgroup/many-linux-with-xapian-bindings:${{inputs.xapian_version}} /scripts/build_wheel.sh
          ls -la `pwd`/wheelhouse
      - name: Upload wheel to GitHub Release                                                                         
        uses: actions/upload-release-asset@v1                                                                        
        env:                                                                                                         
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                                                                  
        with:                                                                                                        
          upload_url: ${{ github.event.release.upload_url }}                                                         
          asset_path: ./dist/*.whl                                                                                   
          asset_name: xapianpy.whl  # Change this to your desired wheel file name                                   
          asset_content_type: application/octet-stream
